# Generated by Django 5.0 on 2025-04-18 12:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("store", "0004_cartitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banner",
            options={
                "ordering": ["sort_order", "-created_at"],
                "verbose_name": "Баннер",
                "verbose_name_plural": "Баннеры",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-order_date"],
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.AlterModelOptions(
            name="promotion",
            options={
                "ordering": ["-start_date", "name"],
                "verbose_name": "Акция",
                "verbose_name_plural": "Акции",
            },
        ),
        migrations.AlterModelOptions(
            name="promotionalproduct",
            options={
                "ordering": ["promotion", "product__name"],
                "verbose_name": "Акционный товар",
                "verbose_name_plural": "Акционные товары",
            },
        ),
        migrations.AddField(
            model_name="banner",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Порядок сортировки"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                verbose_name="Итоговая сумма",
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата окончания"
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Активен"
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="link_url",
            field=models.URLField(max_length=255, verbose_name="URL ссылки"),
        ),
        migrations.AlterField(
            model_name="banner",
            name="position",
            field=models.CharField(
                choices=[
                    ("home_top", "Главная верх"),
                    ("home_middle", "Главная середина"),
                    ("category_top", "Верх категории"),
                    ("product_page", "Страница товара"),
                    ("sidebar", "Боковая панель"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="Позиция на сайте",
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="start_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата начала"
            ),
        ),
        migrations.AlterField(
            model_name="bannertarget",
            name="target_id",
            field=models.PositiveIntegerField(verbose_name="ID цели"),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="store.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="store.deliverymethod",
                verbose_name="Способ доставки",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="store.paymentmethod",
                verbose_name="Способ оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="store.orderstatus",
                verbose_name="Статус заказа",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="store.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="qty",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Количество",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="store.brand",
                verbose_name="Бренд",
            ),
        ),
        migrations.AlterField(
            model_name="productfeaturevalue",
            name="feature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_values",
                to="store.feature",
                verbose_name="Характеристика",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("percentage", "Процент"),
                    ("fixed", "Фиксированная сумма"),
                    ("special_price", "Специальная цена"),
                ],
                help_text="Тип скидки, применяемый к товарам (если не 'Специальная цена')",
                max_length=50,
                verbose_name="Тип скидки",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Процент (напр., 10 для 10%) или фиксированная сумма",
                max_digits=10,
                verbose_name="Значение скидки",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата окончания"
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Активна"
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="start_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата начала"
            ),
        ),
        migrations.AlterField(
            model_name="promotionalproduct",
            name="promotional_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Укажите, если тип скидки 'Специальная цена'. Иначе будет рассчитана автоматически.",
                max_digits=12,
                null=True,
                verbose_name="Акционная цена",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="store_user_groups",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="store_user_permissions",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together={("order", "product")},
        ),
        migrations.AlterUniqueTogether(
            name="productfeaturevalue",
            unique_together={("product", "feature")},
        ),
        migrations.CreateModel(
            name="WishlistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_items",
                        to="store.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент списка желаний",
                "verbose_name_plural": "Элементы списка желаний",
                "ordering": ["-added_at"],
                "unique_together": {("user", "product")},
            },
        ),
        migrations.AddField(
            model_name="user",
            name="wishlist_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="wishlisted_by_users",
                through="store.WishlistItem",
                to="store.product",
                verbose_name="Товары в списке желаний",
            ),
        ),
    ]
