# Generated by Django 5.0 on 2025-05-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_banner_options_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(
                upload_to="media/banners/", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата начала"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/products/",
                verbose_name="Изображение",
            ),
        ),
    ]
